### ISSUE TITLE
ConnectionClosedError: received 4004

### ISSUE THREAD

**Issue by Technik-Tueftler** [Technik-Tueftler/TwitchHenCommander#33]
`loop.run_until_complete(asyncio.gather(*tasks_to_start))
Traceback (most recent call last):
  File "/user/app/TwitchHenCommander/source/main.py", line 65, in <module>
    main()
  File "/user/app/TwitchHenCommander/source/main.py", line 61, in main
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/user/app/TwitchHenCommander/source/twitch_api_websocket.py", line 22, in websocket_listener
    message = json.loads(await connection.recv())
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 948, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: received 4004 (private use) client reconnect grace time expired; then sent 4004 (private use) client reconnect grace time expired`

**Comment by Technik-Tueftler** [comment]
Check websocket implementation in #35 and add logging for 1st websocket implementation
