### ISSUE TITLE
Error at stream-end

### ISSUE THREAD

**Issue by Technik-Tueftler** [Technik-Tueftler/TwitchHenCommander#59]
await func(*args)
  File "/usr/local/lib/python3.11/site-packages/twitchio/client.py", line 208, in wrapped
Traceback (most recent call last):
  File "/user/app/TwitchHenCommander/source/twitch_bot.py", line 71, in event_message
    if await check_if_hash_authorized(message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/user/app/TwitchHenCommander/source/twitch_bot.py", line 40, in check_if_hash_authorized
    if message.author.is_subscriber:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WhisperChatter' object has no attribute 'is_subscriber'

**Comment by Technik-Tueftler** [comment]
closed
